"""compose key stadiums

Revision ID: ac443aad91b6
Revises: 
Create Date: 2026-01-12 23:17:30.941953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac443aad91b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stadiums',
    sa.Column('NAME', sa.String(length=100), nullable=True),
    sa.Column('CITY', sa.String(length=50), nullable=True),
    sa.Column('COUNTRY', sa.String(length=50), nullable=True),
    sa.Column('CAPACITY', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('NAME', 'COUNTRY', name='stadiums_pk')
    )
    op.create_table('teams',
    sa.Column('TEAM_NAME', sa.String(length=100), nullable=True),
    sa.Column('COUNTRY', sa.String(length=50), nullable=True),
    sa.Column('HOME_STADIUM', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('TEAM_NAME')
    )
    op.create_table('managers',
    sa.Column('MANAGER_ID', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('FIRST_NAME', sa.String(length=50), nullable=True),
    sa.Column('LAST_NAME', sa.String(length=50), nullable=True),
    sa.Column('NATIONALITY', sa.String(length=50), nullable=True),
    sa.Column('DOB', sa.Date(), nullable=True),
    sa.Column('TEAM', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['TEAM'], ['teams.TEAM_NAME'], ),
    sa.PrimaryKeyConstraint('MANAGER_ID')
    )
    op.create_table('matches',
    sa.Column('MATCH_ID', sa.String(), nullable=True),
    sa.Column('SEASON', sa.String(length=20), nullable=True),
    sa.Column('DATE_TIME', sa.DateTime(), nullable=True),
    sa.Column('HOME_TEAM', sa.String(length=100), nullable=True),
    sa.Column('AWAY_TEAM', sa.String(length=100), nullable=True),
    sa.Column('STADIUM', sa.String(length=100), nullable=True),
    sa.Column('HOME_TEAM_SCORE', sa.Integer(), nullable=True),
    sa.Column('AWAY_TEAM_SCORE', sa.Integer(), nullable=True),
    sa.Column('PENALTY_SHOOT_OUT', sa.Integer(), nullable=True),
    sa.Column('ATTENDANCE', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['AWAY_TEAM'], ['teams.TEAM_NAME'], ),
    sa.ForeignKeyConstraint(['HOME_TEAM'], ['teams.TEAM_NAME'], ),
    sa.PrimaryKeyConstraint('MATCH_ID')
    )
    op.create_table('players',
    sa.Column('PLAYER_ID', sa.String(), nullable=True),
    sa.Column('FIRST_NAME', sa.String(length=50), nullable=True),
    sa.Column('LAST_NAME', sa.String(length=50), nullable=True),
    sa.Column('NATIONALITY', sa.String(length=50), nullable=True),
    sa.Column('DOB', sa.Date(), nullable=True),
    sa.Column('TEAM', sa.String(length=100), nullable=True),
    sa.Column('JERSEY_NUMBER', sa.Integer(), nullable=True),
    sa.Column('POSITION', sa.String(length=30), nullable=True),
    sa.Column('HEIGHT', sa.Integer(), nullable=True),
    sa.Column('WEIGHT', sa.Integer(), nullable=True),
    sa.Column('FOOT', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['TEAM'], ['teams.TEAM_NAME'], ),
    sa.PrimaryKeyConstraint('PLAYER_ID')
    )
    op.create_table('goals',
    sa.Column('GOAL_ID', sa.String(), nullable=True),
    sa.Column('MATCH_ID', sa.String(), nullable=True),
    sa.Column('PID', sa.String(), nullable=True),
    sa.Column('DURATION', sa.Integer(), nullable=True),
    sa.Column('ASSIST', sa.String(), nullable=True),
    sa.Column('GOAL_DESC', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ASSIST'], ['players.PLAYER_ID'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['MATCH_ID'], ['matches.MATCH_ID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['PID'], ['players.PLAYER_ID'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('GOAL_ID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goals')
    op.drop_table('players')
    op.drop_table('matches')
    op.drop_table('managers')
    op.drop_table('teams')
    op.drop_table('stadiums')
    # ### end Alembic commands ###
